package com.sbsolutions.rilybricoule.mapper;

import com.sbsolutions.rilybricoule.dto.CouponDTO;
import com.sbsolutions.rilybricoule.entity.Coupon;
import org.springframework.stereotype.Component;

/**
 * Mapper for converting between Coupon entity and CouponDTO.
 * Ensures clean separation between database entities and API request/response objects.
 * Handles null safety and secure data exposure.
 */
@Component
public class CouponMapper {

    /**
     * Convert Coupon entity to CouponDTO.
     * 
     * @param coupon the Coupon entity to convert
     * @return CouponDTO with all relevant fields, or null if input is null
     */
    public CouponDTO toDTO(Coupon coupon) {
        if (coupon == null) {
            return null;
        }

        return CouponDTO.builder()
            .id(coupon.getId())
            .code(coupon.getCode())
            .description(coupon.getDescription())
            .discountAmount(coupon.getDiscountAmount())
            .discountPercentage(coupon.getDiscountPercentage())
            .expiryDate(coupon.getExpiryDate())
            .active(coupon.getActive())
            .build();
    }

    /**
     * Convert CouponDTO to Coupon entity.
     * Used for creating or updating coupons from API requests.
     * Does not set the ID as it should be generated by database.
     * 
     * @param dto the CouponDTO with source data
     * @return Coupon entity with populated fields, or null if input is null
     */
    public Coupon toEntity(CouponDTO dto) {
        if (dto == null) {
            return null;
        }

        return Coupon.builder()
            .id(dto.getId()) // Only set during updates
            .code(dto.getCode())
            .description(dto.getDescription())
            .discountAmount(dto.getDiscountAmount())
            .discountPercentage(dto.getDiscountPercentage())
            .expiryDate(dto.getExpiryDate())
            .active(dto.getActive() != null ? dto.getActive() : true)
            .build();
    }

    /**
     * Update existing Coupon entity with data from CouponDTO.
     * Preserves ID and other generated fields while updating changeable properties.
     * 
     * @param dto the CouponDTO with updated data
     * @param coupon the existing Coupon entity to update
     * @return the updated Coupon entity
     */
    public Coupon updateEntity(CouponDTO dto, Coupon coupon) {
        if (dto == null) {
            return coupon;
        }

        if (dto.getCode() != null) {
            coupon.setCode(dto.getCode());
        }
        if (dto.getDescription() != null) {
            coupon.setDescription(dto.getDescription());
        }
        if (dto.getDiscountAmount() != null) {
            coupon.setDiscountAmount(dto.getDiscountAmount());
        }
        if (dto.getDiscountPercentage() != null) {
            coupon.setDiscountPercentage(dto.getDiscountPercentage());
        }
        if (dto.getExpiryDate() != null) {
            coupon.setExpiryDate(dto.getExpiryDate());
        }
        if (dto.getActive() != null) {
            coupon.setActive(dto.getActive());
        }

        return coupon;
    }
}
