# Application Configuration
spring.application.name=rilybricoule

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rilybricoule_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




# Server Configuration
server.port=8084