<<<<<<< HEAD
spring.application.name=rilybricoule
spring.datasource.url=jdbc:postgresql://localhost:5432/rilybricoule-db
spring.datasource.username=postgres
spring.datasource.password=azer1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5VGhpc0lzQVN1cGVyU2VjcmV0S2V5
jwt.refresh-expiration=604800000
jwt.expiration=900000
=======
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjbGllbnRAZXhhbXBsZS5jb20iLCJ1c2VySWQiOjEsInJvbGUiOiJDTElFTlQiLCJpYXQiOjE3NzAxNDQ1NjUsImV4cCI6MTc3MDIzMDk2NX0.3K_vliqVWWumZhthyfAesQmXh_IOy9ZmQItxW7qNpSBHZFC4gq5x4P_z4uh6sHvQ
jwt.expiration=86400000

# Server Configuration
server.port=8084
>>>>>>> 2cabcbd (Implement Auth: Client / Prestataire / Admin)

